export const KEYS = {
	// STATE (Recoil)
	RECOIL_KEY: "RECOIL_KEY",
	STORED_HASHED_VALUES_STATE: "STORED_HASHED_VALUES_STATE",
	BLOCKCHAIN_STATE: "BLOCKCHAIN_STATE",
	HEADER_DATA_INPUT_STATE: "HEADER_DATA_INPUT_STATE",
	BODY_DATA_INPUT_STATE: "BODY_DATA_INPUT_STATE",
	
	// API (React-query)
	ASYNC_KEY: "ASYNC_KEY",
};
